server:
  port: 0


spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
    driverClassName: org.postgresql.Driver
  liquibase:
    changeLog: classpath:liquibase/changelog-master.yml
  application:
    name: ms-payment

#client:
#  ms-country:
#    endpoint: http://localhost:8761

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

management:
  health:
    circuit-breakers:
      enabled: true
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: count_based
        slidingWindowSize: 50
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 60
        eventConsumerBufferSize: 20
      getAllAvailableCountriesConfig:
        sliding-window-type:
        slidingWindowSize: 50
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 60
        eventConsumerBufferSize: 20
    instances:
      myCircuitBreaker:
        baseConfig: default
      getAvailablityBreaker:
        baseConfig: getAllAvailableCountriesConfig
