server:
  port: 8085

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
    driverClassName: org.postgresql.Driver
  liquibase:
    changeLog: classpath:liquibase/changelog-master.yml

client:
  ms-country:
    endpoint: http://localhost:8081

management:
  health:
    circuit-breakers:
      enabled: true
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type:
        slidingWindowSize: 50
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 60
        eventConsumerBufferSize: 20
      getAllAvailableCountriesConfig:
        sliding-window-type:
        slidingWindowSize: 50
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 60
        eventConsumerBufferSize: 20
    instances:
      myCircuitBreaker:
        baseConfig: default
      myCustomCircuitBreaker:
        baseConfig: getAllAvailableCountriesConfig
