spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri:
          search-paths:

logging:
  level:
    root: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
  instance:
    prefer-ip-address: true

server:
  port: 8889


